name: oidc-test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  whoami:
    runs-on: ubuntu-latest
    steps:
      - name: Autenticar en AWS con OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_DEV }}
          aws-region: us-east-1

      - name: Quién soy
        run: aws sts get-caller-identity